#!/bin/bash

_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "moussapro-bot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL01PVVNTQS1BUi9tb3Vzc2Fwcm8tYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $UPSTREAM_REPO == "moussapro-bot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL01PVVNTQS1BUi9tb3Vzc2Fwcm8tYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL01PVVNTQS1BUi9tb3Vzc2Fwcm8tYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    fi
}


_setting_bot () {
    local zippath
    zippath="ProUserBot.zip"
    echo "  يتم تحميل ملفات سورس برو ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  جمع بيانات السورس ..."
    PROPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "✓"
    echo "  يتم الإنشاء.."
    rm -rf "$zippath"
    sleep 5
    cd $PROPATH
    echo "    بدء تشغيل البوت برو    "
    echo "
                       
.____.   .____.      _____
|    |   |    |     /     \
|____|   |____|    |       |
|        | \       |       |
|        |  \      |       |
|        |   \      \_____/
    
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_setting_bot
